FROM python:3.7

WORKDIR /SpiderController

COPY mainController.py .
COPY config.py .
COPY requirements.txt .
COPY templates/mainPage.html templates/

RUN pip install -r requirements.txt

ENV FLASK_APP mainController.py
ENV FLASK_RUN_HOST 0.0.0.0
ENV FLASK_ENV=development

EXPOSE 5000
EXPOSE 5672
EXPOSE 5432

CMD sleep 20 && flask run