name: test_before_pushing
on: push

jobs:
  autocheck:
    run-on: windows-latest
    steps:
      - name: black check
        run: |
          SpiderController\virtualPyCon\Scripts\activate
          black SpiderController\mainController.py
          black SpiderController\config.py
          black SpiderController\tests
          black SpiderWalker\SpiderWalker.py
          black SpiderWalker\tests
        shell: cmd

      - name: flake8 check
        run: |
          SpiderController\virtualPyCon\Scripts\activate
          flake8 SpiderController\mainController.py
          flake8 SpiderController\config.py
          flake8 --ignore F401 SpiderController\tests
          flake8 SpiderWalker\SpiderWalker.py
          flake8 --ignore F401 SpiderWalker\tests
        shell: cmd
  test:
    run-on: windows-latest
    needs: autocheck
    steps:
      - name: walker test
        run: |
          SpiderWalker\virtualPy\Scripts\activate
          python SpiderWalker\tests\SpiderWalker_test.py
        shell: cmd