name: test_before_pushing
on: push

jobs:
  autocheck:
    runs-on: windows-latest
    steps:
      - name: black check
        run: |
          SpiderController\virtualPyCon\Scripts\activate
          SpiderController\virtualPyCon\Scripts\black SpiderController\mainController.py
          SpiderController\virtualPyCon\Scripts\black SpiderController\config.py
          SpiderController\virtualPyCon\Scripts\black SpiderController\tests
          SpiderController\virtualPyCon\Scripts\black SpiderWalker\SpiderWalker.py
          SpiderController\virtualPyCon\Scripts\black SpiderWalker\tests
        shell: cmd

      - name: flake8 check
        run: |
          SpiderController\virtualPyCon\Scripts\activate
          SpiderController\virtualPyCon\Scripts\flake8 SpiderController\mainController.py
          SpiderController\virtualPyCon\Scripts\flake8 SpiderController\config.py
          SpiderController\virtualPyCon\Scripts\flake8 --ignore F401 SpiderController\tests
          SpiderController\virtualPyCon\Scripts\flake8 SpiderWalker\SpiderWalker.py
          SpiderController\virtualPyCon\Scripts\flake8 --ignore F401 SpiderWalker\tests
        shell: cmd
  test:
    runs-on: windows-latest
    needs: autocheck
    steps:
      - name: walker test
        run: |
          SpiderWalker\virtualPy\Scripts\activate
          python SpiderWalker\tests\SpiderWalker_test.py
        shell: cmd