name: test_before_pushing
on:
  pull_request:
    branches: [$default-branch] 
  push:

jobs:
  check:
    runs-on: ubuntu-latest, windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7' 
          architecture: 'x86'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest black
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: flake8 check
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: black check
        run: |
          black .
      - name: test with pytest
        run: |
          pytest